=== maryna25/oop_term5/labs/lab2/schema.xsd
<?xml version = "1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/Club" xmlns="http://www.example.com/Club">
    <xs:element name="schema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="beers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="beer" type="BeerType" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="IngridientsType">
        <xs:sequence>
            <xs:element name="ingridient" minOccurs="0" maxOccurs="200">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SpillMethodType">
        <xs:sequence>
            <xs:element name = "capacity" type = "xs:positiveInteger"/>
            <xs:element name = "material" type = "xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CharsType">
        <xs:sequence>
            <xs:element name = "revolNumber" type = "xs:positiveInteger" minOccurs="0" maxOccurs="1" />
            <xs:element name = "transparency" type = "xs:positiveInteger"/>
            <xs:element name = "filtered" type = "xs:boolean"/>
            <xs:element name = "nutritionalValue" type = "xs:positiveInteger"/>
            <xs:element name = "spillMethod" type = "SpillMethodType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "BeerType">
        <xs:sequence>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "type">
            <xs:simpleType>
                <xs:restriction base="xs:normalizedString">
                    <xs:enumeration value="dark"/>
                    <xs:enumeration value="light"/>
                    <xs:enumeration value="alive"/>
                    <xs:enumeration value="camp"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
            <xs:element name = "al" type = "xs:boolean"/>
            <xs:element name = "manufacturer" type = "xs:string"/>
	        <xs:element name = "ingridients" type = "IngridientsType"/>
            <xs:element name = "chars" type = "CharsType"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== maryna25/oop_term5/labs/lab2/Beer.xml
<?xml version="1.0" encoding="utf-8"?>
<tns:schema xmlns:tns="http://www.example.com/Club" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/shema schema.xsd ">
    <beers>
        <beer>
            <name>beer1</name>
            <type>light</type>
            <al>true</al>
            <manufacturer>m1</manufacturer>
	        <ingridients>
                <ingridient>i1</ingridient>
                <ingridient>i2</ingridient>
            </ingridients>
            <chars>
                <revolNumber>10</revolNumber>
                <transparency>50</transparency>
                <filtered>false</filtered>
                <nutritionalValue>115</nutritionalValue>
                <spillMethod>
                    <capacity>12</capacity>
                    <material>material1</material>
                </spillMethod>
            </chars>
        </beer>

	<beer>
            <name>beer2</name>
            <type>dark</type>
            <al>true</al>
            <manufacturer>m2</manufacturer>
            <ingridients>
                <ingridient>i1</ingridient>
                <ingridient>i2</ingridient>
            </ingridients>
            <chars>
                <revolNumber>30</revolNumber>
                <transparency>20</transparency>
                <filtered>false</filtered>
                <nutritionalValue>137</nutritionalValue>
                <spillMethod>
                    <capacity>15</capacity>
                    <material>material1</material>
                </spillMethod>
            </chars>
        </beer>0

	<beer>
            <name>beer3</name>
            <type>dark</type>
            <al>false</al>
            <manufacturer>m3</manufacturer>
            <ingridients>
                <ingridient>i1</ingridient>
                <ingridient>i2</ingridient>
            </ingridients>
            <chars>
                <transparency>50</transparency>
                <filtered>false</filtered>
                <nutritionalValue>300</nutritionalValue>
                <spillMethod>
                    <capacity>12</capacity>
                    <material>material1</material>
                </spillMethod>
            </chars>
        </beer>
    </beers>
</tns:schema>
